import Head from "next/head";
import localFont from "next/font/local";
import styles from "@/styles/Home.module.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>Jeehoon FrontEnd Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <main className={styles.main}>

        </main>
        <footer className={styles.footer}>
          
        </footer>
      </div>
    </>
  );
}
