import { Translation } from '@/i18n/types';

export const meta: Translation = {
    title: 'Jeehoon | FrontEnd Portfolio',
    description: 'Generated by create next app',
    viewport: 'width=device-width, initial-scale=1',
};
