import Head from 'next/head';
import React from 'react';

export const Meta = () => {
	return (
		<Head>
            <title>Jeehoon | FrontEnd Portfolio</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
		</Head>
	);
};

Meta.displayName = 'Meta';
