import { Translation } from '@/i18n/types';

export const aboutMe: Translation = {
    title: 'AboutMe',
    introduction: '반갑습니다,<br />프론트엔드 개발자 박지훈입니다.',
    description: 'Generated by create next app',
    viewport: 'width=device-width, initial-scale=1',
};
